// Playwright config for the P7-04 end-to-end smoke test.
//
// The app has no build step of its own beyond what's already committed
// (`pkg/`, `dist/output.css`) - it's served as static files. `webServer`
// below reuses the same plain HTTP server `serve.sh`/`serve.bat` use for
// local development, so CI and a developer's machine exercise the exact
// same serving setup.
//
// Run with `npm run test:e2e` (see package.json). Requires
// `npx playwright install chromium` once per machine (not committed -
// browser binaries are large and machine-specific, same reasoning as
// `pkg/` being gitignored and regenerated by `wasm-pack build`).
const { defineConfig, devices } = require("@playwright/test");

module.exports = defineConfig({
  testDir: "./tests/e2e",
  timeout: 30_000,
  fullyParallel: false,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? "line" : "list",
  use: {
    baseURL: "http://127.0.0.1:8080",
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    command: "python3 -m http.server 8080 --bind 127.0.0.1",
    url: "http://127.0.0.1:8080",
    reuseExistingServer: !process.env.CI,
    timeout: 30_000,
  },
});
