// Phase P9 end-to-end test: word suggestion popup.
//
// Uses the real dictionary (`dist/dictionary/01_kv.tsv`, generated by
// `npm run prepare:dict` - already present in this checkout) rather
// than a fixture, since the feature's whole point is surfacing real
// dictionary content. "аалз" (spider) was picked by inspecting the TSV
// directly: it's the *only* single-word entry with that exact prefix
// after phrase-entry filtering (its near-neighbor "аалзны" is excluded
// because its Mongolian value "ᠠᠭᠠᠯᠵᠢᠨ ᠤ" contains a space), so the
// suggestion this test expects is deterministic, not just "some
// suggestion appeared."
//
// The Latin->Mongolian input mode maps *some* Cyrillic letter keys too
// (confirmed via config/latin.csv - е.g. "а"/"л"/"з" are all mapped),
// so every test here turns input mode off first, matching the
// convention already used in smoke.spec.js/latin-mapping.spec.js, to
// guarantee raw Cyrillic reaches the buffer unconverted.
const { test, expect } = require("@playwright/test");

async function waitForReady(page) {
  await page.waitForFunction(() => window.__unsTestHooks?.isReady() === true, {
    timeout: 30_000,
  });
  await expect(page.locator("#loading")).toBeHidden();
}

async function prepareBlankCyrillicInput(page) {
  await page.locator("#keyboard-btn").click(); // turn off Latin->Mongolian conversion
  await page.locator("#clear-btn").click();
  await page.locator("#editor-canvas").click();
}

// `page.keyboard.type()` synthesizes real `keydown`/`keyup` events only
// for characters that exist on Playwright's built-in US keyboard layout
// - for anything else (Cyrillic here) it silently falls back to a
// CDP `Input.insertText` call, which has nothing to insert into since
// `#editor-canvas` is a `<canvas>`, not a native editable element. The
// app's own input handling is entirely `keydown`-event driven (see
// `index.html`'s canvas listener), so it never receives those
// characters at all via `.type()`. Dispatching `KeyboardEvent`s
// directly - which only need a real `.key` string, exactly what the
// app's handler reads - sidesteps the limitation. (Confirmed by manual
// testing: `.type("а")` on a freshly cleared buffer leaves it empty,
// while dispatching a `keydown` with `key: "а"` inserts it correctly.)
async function typeCyrillic(page, text) {
  for (const ch of text) {
    await page.evaluate((key) => {
      document
        .getElementById("editor-canvas")
        .dispatchEvent(
          new KeyboardEvent("keydown", { key, bubbles: true, cancelable: true }),
        );
    }, ch);
  }
}

test.describe("Word suggestion popup (Phase P9)", () => {
  test("typing a Cyrillic prefix shows a Mongolian suggestion; Enter accepts it", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    await expect(popup.locator("li")).toHaveCount(1);
    // `li`'s own text includes the numbered-column badge (see
    // `render()`) - `.suggestion-word` isolates just the word itself.
    await expect(popup.locator("li").first().locator(".suggestion-word")).toHaveText(
      "\u1820\u182d\u1820\u182f\u1835\u1822",
    );

    await page.keyboard.press("Enter");

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("\u1820\u182d\u1820\u182f\u1835\u1822");
  });

  test("Escape dismisses the popup without changing the buffer", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");
    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();

    await page.keyboard.press("Escape");
    await expect(popup).toBeHidden();

    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("аалз");
  });

  test("arrow keys navigate multiple suggestions; mouse click accepts", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // "аа" alone matches many single-word entries - enough to exercise
    // navigation without needing to know the exact ranked order.
    await typeCyrillic(page, "аа");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    // Vertical mode (the default - see `prepareBlankCyrillicInput`'s
    // caller context) renders each suggestion as its own numbered
    // column (`WordSuggestionsPopup.render()`), not a stacked list -
    // `li.textContent` therefore includes both the number badge and
    // the word; `.suggestion-word` isolates just the word.
    const items = popup.locator("li");
    const count = await items.count();
    // "аа" alone matches 58 single-word entries after phrase filtering
    // (verified against the real TSV) - well over SUGGESTION_LIMIT (8),
    // so this also exercises the ranking/cap logic in `Dictionary::suggest`.
    expect(count).toBeGreaterThan(1);
    expect(count).toBeLessThanOrEqual(8);

    // First item starts selected.
    await expect(items.nth(0)).toHaveClass(/bg-editor-accent/);

    await page.keyboard.press("ArrowDown");
    await expect(items.nth(0)).not.toHaveClass(/bg-editor-accent/);
    await expect(items.nth(1)).toHaveClass(/bg-editor-accent/);

    // Click a different item directly (not necessarily the selected
    // one) - accepting by mouse doesn't require it to be highlighted
    // first.
    const acceptedText = await items
      .nth(count - 1)
      .locator(".suggestion-word")
      .textContent();
    await items.nth(count - 1).click();

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe(acceptedText);
  });

  test("Left/Right arrows navigate the numbered columns in vertical mode without dismissing", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // Default orientation is vertical (see word-suggestions-vertical
    // rendering) - the popup lays suggestions out as a horizontal row
    // of numbered columns there, so Left/Right is the natural
    // navigation axis (as opposed to horizontal mode's single-column
    // stacked list, where Up/Down is the only navigation axis and
    // Left/Right keeps moving the text cursor instead - covered by the
    // "Escape dismisses" test's sibling assumptions elsewhere).
    await typeCyrillic(page, "аа");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    const items = popup.locator("li");

    await expect(items.nth(0)).toHaveClass(/bg-editor-accent/);

    await page.keyboard.press("ArrowRight");
    await expect(popup).toBeVisible();
    await expect(items.nth(0)).not.toHaveClass(/bg-editor-accent/);
    await expect(items.nth(1)).toHaveClass(/bg-editor-accent/);

    await page.keyboard.press("ArrowRight");
    await expect(items.nth(2)).toHaveClass(/bg-editor-accent/);

    await page.keyboard.press("ArrowLeft");
    await expect(items.nth(1)).toHaveClass(/bg-editor-accent/);

    const secondWord = await items.nth(1).locator(".suggestion-word").textContent();
    await page.keyboard.press("Enter");

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe(secondWord);
  });

  test("number keys accept the corresponding numbered column directly", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аа");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    const items = popup.locator("li");
    const count = await items.count();
    expect(count).toBeGreaterThanOrEqual(3);

    const thirdWord = await items.nth(2).locator(".suggestion-word").textContent();
    await page.keyboard.press("3");

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe(thirdWord);
  });

  test("a number key beyond the available suggestions falls through to normal typing", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // "аалз" has exactly one match (see the module doc comment above) -
    // pressing "9" should just insert the digit "9", not silently do
    // nothing.
    await typeCyrillic(page, "аалз");
    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    await expect(popup.locator("li")).toHaveCount(1);

    await page.keyboard.press("9");

    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("аалз9");
  });

  test("disabling word suggestions in settings prevents the popup from appearing", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await page.locator("#settings-btn").click();
    await page.locator("#editor-tab-btn").click();
    await page.locator("#word-suggestions-enabled").uncheck();
    await page.locator("#settings-save").click();

    await page.locator("#editor-canvas").click();
    await typeCyrillic(page, "аалз");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeHidden();
    // Confirm typing itself still works normally with the feature off.
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("аалз");
  });

  test("switching tabs dismisses the popup", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");
    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();

    await page.locator("#tab-strip-new-btn").click();
    await expect(popup).toBeHidden();
  });
});
