// Phase P9 end-to-end test: word suggestion popup.
//
// Uses the real dictionary (`dist/dictionary/01_kv.tsv`, generated by
// `npm run prepare:dict` - already present in this checkout) rather
// than a fixture, since the feature's whole point is surfacing real
// dictionary content. "аалз" (spider) was picked by inspecting the TSV
// directly: it's the *only* single-word entry with that exact prefix
// after phrase-entry filtering (its near-neighbor "аалзны" is excluded
// because its Mongolian value "ᠠᠭᠠᠯᠵᠢᠨ ᠤ" contains a space), so the
// suggestion this test expects is deterministic, not just "some
// suggestion appeared."
//
// The Latin->Mongolian input mode maps *some* Cyrillic letter keys too
// (confirmed via config/latin.csv - е.g. "а"/"л"/"з" are all mapped),
// so every test here turns input mode off first, matching the
// convention already used in smoke.spec.js/latin-mapping.spec.js, to
// guarantee raw Cyrillic reaches the buffer unconverted.
//
// WS-09: the popup's suggestions are drawn into a `cosmic-text`-rendered
// `<canvas>` (see `DOC/IMPL/WORD_SUGGESTIONS_IMPL.md`'s WS-09 section),
// not DOM `<li>` elements, so there's no DOM text to assert against -
// tests use `window.__unsTestHooks.getSuggestionsState()` (exposing the
// same `WordSuggestionsPopup` state the canvas is drawn from) instead of
// querying `#word-suggestions-popup`'s children.
const { test, expect } = require("@playwright/test");

async function waitForReady(page) {
  await page.waitForFunction(() => window.__unsTestHooks?.isReady() === true, {
    timeout: 30_000,
  });
  await expect(page.locator("#loading")).toBeHidden();
}

async function prepareBlankCyrillicInput(page) {
  await page.locator("#keyboard-btn").click(); // turn off Latin->Mongolian conversion
  await page.locator("#clear-btn").click();
  await page.locator("#editor-canvas").click();
}

// `page.keyboard.type()` synthesizes real `keydown`/`keyup` events only
// for characters that exist on Playwright's built-in US keyboard layout
// - for anything else (Cyrillic here) it silently falls back to a
// CDP `Input.insertText` call, which has nothing to insert into since
// `#editor-canvas` is a `<canvas>`, not a native editable element. The
// app's own input handling is entirely `keydown`-event driven (see
// `index.html`'s canvas listener), so it never receives those
// characters at all via `.type()`. Dispatching `KeyboardEvent`s
// directly - which only need a real `.key` string, exactly what the
// app's handler reads - sidesteps the limitation. (Confirmed by manual
// testing: `.type("а")` on a freshly cleared buffer leaves it empty,
// while dispatching a `keydown` with `key: "а"` inserts it correctly.)
async function typeCyrillic(page, text) {
  for (const ch of text) {
    await page.evaluate((key) => {
      document
        .getElementById("editor-canvas")
        .dispatchEvent(
          new KeyboardEvent("keydown", { key, bubbles: true, cancelable: true }),
        );
    }, ch);
  }
}

// The canvas key handler accepts any single-character key, so this also
// drives literal Bichig input after Latin conversion is disabled.
async function typeMongolian(page, text) {
  await typeCyrillic(page, text);
}

function getSuggestionsState(page) {
  return page.evaluate(() => window.__unsTestHooks.getSuggestionsState());
}

test.describe("Word suggestion popup (Phase P9)", () => {
  test("typing a Cyrillic prefix shows a Mongolian suggestion; Enter accepts it", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    let state = await getSuggestionsState(page);
    expect(state.suggestions).toEqual(["\u1820\u182d\u1820\u182f\u1835\u1822"]);
    expect(state.selected).toBe(0);
    // The canvas was actually sized/drawn into, not left at its
    // zero-by-default markup size.
    const canvasSize = await page.evaluate(() => {
      const c = document.getElementById("word-suggestions-canvas");
      return { width: c.width, height: c.height };
    });
    expect(canvasSize.width).toBeGreaterThan(0);
    expect(canvasSize.height).toBeGreaterThan(0);

    await page.keyboard.press("Enter");

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("\u1820\u182d\u1820\u182f\u1835\u1822");
  });

  test("Escape dismisses the popup without changing the buffer", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");
    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();

    await page.keyboard.press("Escape");
    await expect(popup).toBeHidden();

    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("аалз");
  });

  test("NNBSP after an exact Bichig noun offers case suffixes", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // "ном" is an exact single-word dictionary entry (ᠨᠣᠮ). It keeps
    // ordinary dictionary completion until the user presses '-' in Latin
    // input mode. That key buffers NNBSP rather than inserting it, which
    // is the production path the suffix request must support.
    await typeMongolian(page, "\u1828\u1823\u182e");
    let state = await getSuggestionsState(page);
    expect(state.suggestions).toContain("\u1828\u1823\u182e");
    await page.locator("#keyboard-btn").click();
    await page.keyboard.press("-");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    state = await getSuggestionsState(page);
    expect(state.suggestions).toContain("\u1824\u1828"); // genitive -un
    expect(state.suggestions).toContain("\u1833\u1824"); // dative-locative -du
    expect(state.suggestions).toContain("\u1833\u1824\u1837"); // alternate -dur

    const genitiveIndex = state.suggestions.indexOf("\u1824\u1828");
    await page.keyboard.press(String(genitiveIndex + 1));

    // Selecting a noun case advances directly to its reflexive-possessive
    // alternatives without requiring a second separator keystroke.
    await expect(popup).toBeVisible();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("\u1828\u1823\u182e\u202f\u1824\u1828");
    state = await getSuggestionsState(page);
    expect(state.suggestions).toContain("\u1822\u1836\u1820\u1828"); // genitive -iyan
  });

  test("NNBSP after a manually written noun case opens possessive choices", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // Write ном и manually, then request the next grammatical suffix.
    await typeMongolian(page, "\u1828\u1823\u182e");
    await page.locator("#keyboard-btn").click();
    await page.keyboard.press("-");
    await page.keyboard.press("i"); // Latin mapping -> ᠢ
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("\u1828\u1823\u182e\u202f\u1822");
    await page.keyboard.press("-");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    const state = await getSuggestionsState(page);
    // Short accusative-reflexive form has priority and replaces ᠢ.
    expect(state.suggestions[0]).toBe("\u1836\u1824\u182D\u1820\u1828");

    await page.keyboard.press("Enter");
    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("\u1828\u1823\u182e\u202f\u1836\u1824\u182D\u1820\u1828");
  });

  test("a manually typed feminine stem gets unique suffix suggestions", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // The keyboard's g/e/r mapping produces ᠭᠡᠷ, while the dictionary
    // stores a different initial-glyph variant. Suffix harmony must use
    // the manually typed Bichig vowels, not require dictionary equality.
    await typeMongolian(page, "\u182d\u1821\u1837");
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("\u182d\u1821\u1837");
    await page.locator("#keyboard-btn").click();
    await page.keyboard.press("-");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    const state = await getSuggestionsState(page);
    expect(state.suggestions).toContain("\u1826\u1828"); // genitive -ün
    expect(state.suggestions).toContain("\u1832\u1826"); // dative-locative -tü
    expect(state.suggestions).toContain("\u1821\u1834\u1821"); // ablative -eče
    expect(new Set(state.suggestions).size).toBe(state.suggestions.length);
  });

  test("arrow keys navigate multiple suggestions; mouse click accepts", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // "аа" alone matches many single-word entries - enough to exercise
    // navigation without needing to know the exact ranked order.
    await typeCyrillic(page, "аа");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    let state = await getSuggestionsState(page);
    // "аа" alone matches 58 single-word entries after phrase filtering
    // (verified against the real TSV) - well over SUGGESTION_LIMIT (8),
    // so this also exercises the ranking/cap logic in `Dictionary::suggest`.
    expect(state.suggestions.length).toBeGreaterThan(1);
    expect(state.suggestions.length).toBeLessThanOrEqual(8);
    expect(state.selected).toBe(0);

    await page.keyboard.press("ArrowDown");
    state = await getSuggestionsState(page);
    expect(state.selected).toBe(1);

    // Click a different item directly (not necessarily the selected
    // one) - accepting by mouse doesn't require it to be highlighted
    // first. Click the last suggestion's hit-box, computed from
    // `itemBounds` (device-pixel space) converted back to CSS-pixel
    // page coordinates the same way `position()` does the reverse.
    const lastIndex = state.suggestions.length - 1;
    const acceptedText = state.suggestions[lastIndex];
    const bounds = state.itemBounds[lastIndex];
    const canvasBox = await page.locator("#word-suggestions-canvas").boundingBox();
    const dpr = await page.evaluate(() => window.devicePixelRatio || 1);
    await page.mouse.click(
      canvasBox.x + (bounds.x + bounds.w / 2) / dpr,
      canvasBox.y + (bounds.y + bounds.h / 2) / dpr,
    );

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe(acceptedText);
  });

  test("Left/Right arrows navigate the numbered columns in vertical mode without dismissing", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // Default orientation is vertical - the popup lays suggestions out
    // as a horizontal row of numbered columns there, so Left/Right is
    // the natural navigation axis (as opposed to horizontal mode's
    // single-column stacked list, where Up/Down is the only navigation
    // axis and Left/Right keeps moving the text cursor instead).
    await typeCyrillic(page, "аа");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    let state = await getSuggestionsState(page);
    expect(state.selected).toBe(0);

    await page.keyboard.press("ArrowRight");
    await expect(popup).toBeVisible();
    state = await getSuggestionsState(page);
    expect(state.selected).toBe(1);

    await page.keyboard.press("ArrowRight");
    state = await getSuggestionsState(page);
    expect(state.selected).toBe(2);

    await page.keyboard.press("ArrowLeft");
    state = await getSuggestionsState(page);
    expect(state.selected).toBe(1);

    const secondWord = state.suggestions[1];
    await page.keyboard.press("Enter");

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe(secondWord);
  });

  test("number keys accept the corresponding numbered column directly", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аа");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    const state = await getSuggestionsState(page);
    expect(state.suggestions.length).toBeGreaterThanOrEqual(3);

    const thirdWord = state.suggestions[2];
    await page.keyboard.press("3");

    await expect(popup).toBeHidden();
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe(thirdWord);
  });

  test("a number key beyond the available suggestions falls through to normal typing", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    // "аалз" has exactly one match (see the module doc comment above) -
    // pressing "9" should just insert the digit "9", not silently do
    // nothing.
    await typeCyrillic(page, "аалз");
    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();
    const state = await getSuggestionsState(page);
    expect(state.suggestions).toHaveLength(1);

    await page.keyboard.press("9");

    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("аалз9");
  });

  test("disabling word suggestions in settings prevents the popup from appearing", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await page.locator("#settings-btn").click();
    await page.locator("#editor-tab-btn").click();
    await page.locator("#word-suggestions-enabled").uncheck();
    await page.locator("#settings-save").click();

    await page.locator("#editor-canvas").click();
    await typeCyrillic(page, "аалз");

    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeHidden();
    // Confirm typing itself still works normally with the feature off.
    await expect
      .poll(() => page.evaluate(() => window.__unsTestHooks.getText().trim()))
      .toBe("аалз");
  });

  test("switching tabs dismisses the popup", async ({ page }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");
    const popup = page.locator("#word-suggestions-popup");
    await expect(popup).toBeVisible();

    await page.locator("#tab-strip-new-btn").click();
    await expect(popup).toBeHidden();
  });

  test("accessibility mirror announces the current suggestion and clears on dismiss", async ({
    page,
  }) => {
    await page.goto("/");
    await waitForReady(page);
    await prepareBlankCyrillicInput(page);

    await typeCyrillic(page, "аалз");
    const mirror = page.locator("#sr-suggestions");
    await expect(mirror).toHaveText(/Suggestion 1 of 1 selected: \u1820\u182d\u1820\u182f\u1835\u1822/);

    await page.keyboard.press("Escape");
    await expect(mirror).toHaveText("");
  });
});
