/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmeditor_free: (a: number, b: number) => void;
export const wasmeditor_get_cursor_position: (a: number) => any;
export const wasmeditor_get_settings_json: (a: number) => [number, number, number, number];
export const wasmeditor_get_text: (a: number) => [number, number];
export const wasmeditor_handle_key_down: (a: number, b: any) => [number, number];
export const wasmeditor_handle_key_up: (a: number, b: any) => void;
export const wasmeditor_handle_mouse_down: (a: number, b: any) => [number, number];
export const wasmeditor_handle_mouse_move: (a: number, b: any) => [number, number];
export const wasmeditor_handle_mouse_up: (a: number, b: any) => [number, number];
export const wasmeditor_handle_touch_end: (a: number, b: any) => [number, number];
export const wasmeditor_handle_touch_move: (a: number, b: any) => [number, number];
export const wasmeditor_handle_touch_start: (a: number, b: any) => [number, number];
export const wasmeditor_handle_wheel: (a: number, b: any) => [number, number];
export const wasmeditor_insert_text: (a: number, b: number, c: number) => void;
export const wasmeditor_new: (a: number, b: number) => any;
export const wasmeditor_render: (a: number, b: number) => [number, number];
export const wasmeditor_set_settings_json: (a: number, b: number, c: number) => [number, number];
export const wasmeditor_set_size: (a: number, b: number, c: number) => void;
export const wasmeditor_set_text: (a: number, b: number, c: number) => void;
export const wasmeditor_toggle_vertical: (a: number) => void;
export const main: () => void;
export const wasm_bindgen__closure__destroy__h9fe21e8b023d8040: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h23f0b2cb1aaf7965: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5ce99ad185dd8d06: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
